-- 🚀 CYBER MART 2077 - DATABASE INITIALIZATION SCRIPT
-- Run this script in PostgreSQL to set up the database

-- Create database (run this as postgres superuser)
-- CREATE DATABASE cybermart2077;

-- Connect to the cybermart2077 database before running the rest

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create admin user (password: admin123)
-- This will be created by the application, but here for reference
-- INSERT INTO users (id, email, username, password_hash, name, role, email_verified) 
-- VALUES (
--   uuid_generate_v4(),
--   'admin@cybermart2077.com',
--   'admin',
--   '$2a$10$hash_here', -- This will be generated by the app
--   'Cyber Admin',
--   'admin',
--   true
-- );

-- Insert sample cyberpunk products
INSERT INTO products (id, name, description, price, category, image_url, stock, tags) VALUES
(uuid_generate_v4(), '🧠 Neural Interface Headset X1000', 'Advanced neural interface technology for direct brain-computer connection. Experience reality beyond imagination with quantum-enhanced processing capabilities.', '2499.99', 'Neural Tech', '/api/placeholder/neural-headset', 50, '["neural", "brain-computer", "quantum", "reality-enhancement"]'),

(uuid_generate_v4(), '⚡ Quantum Processor Core 2077', 'Military-grade quantum processing unit delivering infinite computational power. Break through the limitations of classical computing.', '4999.99', 'Quantum Computing', '/api/placeholder/quantum-processor', 25, '["quantum", "military-grade", "infinite-power", "computational"]'),

(uuid_generate_v4(), '🚀 Cybernetic Enhancement Pack v5.0', 'Complete cybernetic enhancement package for human augmentation. Transcend human limitations with advanced biotechnology.', '7999.99', 'Cybernetics', '/api/placeholder/cybernetic-pack', 15, '["cybernetic", "human-augmentation", "biotechnology", "transcendence"]'),

(uuid_generate_v4(), '🌟 Holographic Display Matrix', 'State-of-the-art holographic projection system. Create immersive 3D environments with photorealistic quality.', '3499.99', 'Display Tech', '/api/placeholder/holographic-display', 30, '["holographic", "3d-projection", "immersive", "photorealistic"]'),

(uuid_generate_v4(), '🔮 AI Consciousness Booster', 'Amplify your cognitive abilities with artificial intelligence enhancement. Unlock the full potential of human consciousness.', '5999.99', 'AI Enhancement', '/api/placeholder/ai-consciousness', 20, '["ai-enhancement", "cognitive-boost", "consciousness", "potential-unlock"]'),

(uuid_generate_v4(), '💎 Nano-Material Exoskeleton', 'Ultra-lightweight exoskeleton made from advanced nano-materials. Provides superhuman strength and agility.', '12999.99', 'Wearable Tech', '/api/placeholder/exoskeleton', 10, '["nano-materials", "exoskeleton", "superhuman", "strength-agility"]'),

(uuid_generate_v4(), '🔋 Fusion Power Cell Array', 'Compact fusion power source providing unlimited clean energy. Revolutionary breakthrough in portable power technology.', '8999.99', 'Energy Tech', '/api/placeholder/fusion-cell', 18, '["fusion-power", "unlimited-energy", "clean-technology", "revolutionary"]'),

(uuid_generate_v4(), '📡 Quantum Communication Device', 'Instantaneous communication across any distance using quantum entanglement. Breakthrough in communication technology.', '6499.99', 'Communication', '/api/placeholder/quantum-comm', 22, '["quantum-entanglement", "instantaneous", "breakthrough", "communication"]');

-- Insert sample analytics events
INSERT INTO analytics_events (id, session_id, event_type, event_data, user_agent, ip_address, timestamp) VALUES
(uuid_generate_v4(), 'session_' || floor(random() * 1000), 'page_view', '{"page": "/", "duration": 1500}', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', '192.168.1.100', NOW() - INTERVAL '1 hour'),
(uuid_generate_v4(), 'session_' || floor(random() * 1000), 'product_view', '{"product_id": "neural-headset", "category": "Neural Tech"}', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', '192.168.1.101', NOW() - INTERVAL '30 minutes'),
(uuid_generate_v4(), 'session_' || floor(random() * 1000), 'add_to_cart', '{"product_id": "quantum-processor", "price": 4999.99}', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36', '192.168.1.102', NOW() - INTERVAL '15 minutes');

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
CREATE INDEX IF NOT EXISTS idx_products_stock ON products(stock);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event_type ON analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_timestamp ON analytics_events(timestamp);

-- Display setup completion message
DO $$
BEGIN
    RAISE NOTICE '🚀 CYBER MART 2077 DATABASE INITIALIZED SUCCESSFULLY!';
    RAISE NOTICE '📊 Sample products created: 8 cyberpunk items';
    RAISE NOTICE '📈 Analytics events initialized';
    RAISE NOTICE '🏗️ Database indexes created';
    RAISE NOTICE '✅ Ready for application startup!';
END $$;
